name: 🧰 Setup LECO Enviroment
inputs:
  cwd:
    default: .
runs:
  using: composite
  steps:
    - run: clang++ -v
      shell: bash
    - run: |
        git clone --depth=1 https://github.com/m4c0/gopt.git
        git clone --depth=1 https://github.com/m4c0/leco.git
        git clone --depth=1 https://github.com/m4c0/minirent.git
        git clone --depth=1 https://github.com/m4c0/mtime.git
        git clone --depth=1 https://github.com/m4c0/popen.git
        git clone --depth=1 https://github.com/m4c0/tempsie.git
      shell: bash
    - run: |
        clang++ -std=c++2b -o build.exe build.cpp
        ./build.exe
      shell: bash
      working-directory: leco
