name: 🧰 Setup LECO Enviroment
inputs:
  cwd:
    default: .
runs:
  using: composite
  steps:
    - run: git clone --depth=1 https://github.com/m4c0/gopt.git gopt
      shell: bash
    - run: git clone --depth=1 https://github.com/m4c0/leco.git leco
      shell: bash
    - run: git clone --depth=1 https://github.com/m4c0/minirent.git minirent
      shell: bash
    - run: git clone --depth=1 https://github.com/m4c0/mtime.git mtime
      shell: bash
    - run: git clone --depth=1 https://github.com/m4c0/popen.git popen
      shell: bash
    - run: git clone --depth=1 https://github.com/m4c0/tempsie.git tempsie
      shell: bash
    - run: clang++ -v
      shell: bash
    - run: clang++ -std=c++2b -o build.exe build.cpp
      shell: bash
      working-directory: leco
    - run: ./build.exe
      shell: bash
      working-directory: leco
